In [1]:
import numpy as np

# Original 1D array
arr1_1d = np.array([1, 2, 3])

# Reshaping 1D array to 2D (1 row, 3 columns)
arr1_1d_to_2d = arr1_1d.reshape(1, -1)
print("1D reshaped to 2D:\n", arr1_1d_to_2d)

# Reshaping 1D array to 3D (1 depth, 1 row, 3 columns)
arr1_1d_to_3d = arr1_1d.reshape(1, 1, -1)
print("1D reshaped to 3D:\n", arr1_1d_to_3d)

# Original 2D array
arr2_2d = np.array([[4, 5, 6], [7, 8, 9]])

# Reshaping 2D array to 3D (1 depth, 2 rows, 3 columns)
arr2_2d_to_3d = arr2_2d.reshape(1, 2, -1)
print("2D reshaped to 3D:\n", arr2_2d_to_3d)

# Demonstration of reshaping a 2D array for concatenation
# If we want to concatenate a 1D array with a 2D array, we first reshape the 1D array
arr1_reshaped_for_concat = arr1_1d.reshape(1, -1)
print("\n1D array reshaped to match 2D array shape for concatenation:\n", arr1_reshaped_for_concat)


1D reshaped to 2D:
 [[1 2 3]]
1D reshaped to 3D:
 [[[1 2 3]]]
2D reshaped to 3D:
 [[[4 5 6]
  [7 8 9]]]

1D array reshaped to match 2D array shape for concatenation:
 [[1 2 3]]


In [19]:
import numpy as np

# Joining 1D with 1D array
arr1_1d = np.array([1, 2, 3])
arr2_1d = np.array([4, 5, 6])

result_1d_1d = np.concatenate((arr1_1d, arr2_1d))
print("1D with 1D:", result_1d_1d)

# Joining 1D with 2D array
arr1_2d = np.array([
    [7, 8, 9], 
    [10, 11, 12]
])

result_1d_2d = np.concatenate((arr1_1d.reshape(1, -1), arr1_2d), axis=0)
print("1D with 2D:\n", result_1d_2d)

# Joining 1D with 3D array
arr1_3d = np.array([
    [
        [13, 14, 15], 
        [16, 17, 18]
    ], 
    [
        [19, 20, 21], 
        [22, 23, 24]
    ]
])

# Joining 2D with 3D array
arr2_2d = np.array([
    [25, 26, 27], 
    [28, 29, 30]
])

result_2d_3d = np.concatenate((arr2_2d.reshape(1, 2, -1), arr1_3d), axis=0)
print("2D with 3D:\n", result_2d_3d)


1D with 1D: [1 2 3 4 5 6]
1D with 2D:
 [[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]
2D with 3D:
 [[[25 26 27]
  [28 29 30]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
